name: run-tests
on: [pull_request]
jobs:
  set-up-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm start
        env:
          DATABASE: mongodb://localhost:27020